export default [
  {
    _createdAt: "",
    _id: "b0e70f9d-60bc-4ef7-8fd3-a183255059e5",
    _rev: "ljxKvzo6Ft3JJjdVmA0hRp",
    _type: "experience",
    _updatedAt: "2022-11-17T07:40:11Z",
    company: "Recipeat",
    dateStarted: "2023-01-01",
    isCurrentlyWorkingHere: true,
    jobTitle: "Frontend Developer",
    points: [
      "Collabrated with designer to make robust React Components",
      "Created various email templates for listmonk",
      "Made different React components for Recipay, a hiring platform for hospitality industry",
      "Worked closely with the CTO of the company on Whatsaap bot to create Resumes",
    ],
  },
  {
    _createdAt: "2022-11-17T07:40:11Z",
    _id: "b0e70f9d-60bc-4ef7-8fd3-a183255059e3",
    _rev: "ljxKvzo6Ft3JJjdVmA0hRl",
    _type: "experience",
    _updatedAt: "2022-11-17T07:40:11Z",
    company: "Viseven",
    dateStarted: "2022-10-17",
    dateEnded: "28-12-2022",
    isCurrentlyWorkingHere: false,
    jobTitle: "Frontend Developer",
    points: [
      "Created templates for eWizard",
      "Worked on Vue.js to create pharmaceutical templates.",
      "Created quality mockups and prototypes",
      "Worked with ewizard.js to develop email briefs for different pharmaceutical companies",
    ],
  },

  {
    _createdAt: "2022-11-17T07:33:10Z",
    _id: "c5e27593-dff2-4e86-92d5-205f00a591ce",
    _rev: "qKicPX1LyXW8uXZ46TdaiQ",
    _type: "experience",
    _updatedAt: "2022-11-17T07:33:10Z",
    company: "Coding Hustle (Youtube Channel)",
    dateStarted: "2022-04-07",
    isCurrentlyWorkingHere: true,
    jobTitle: "Javascript Developer, Founder",
    points: [
      "Created a hindi channel to explain web development",
      "Made multiple tutorials to help students in Javascript",
      "Made multiple projects in ReactJs",
      "Made videos related to blockchain and cypto currency",
    ],
  },
  {
    _createdAt: "2022-11-17T07:00:07Z",
    _id: "81df44d4-c0c7-46f3-9e1f-0c14a8f46f1d",
    _rev: "ljxKvzo6Ft3JJjdVm9wjeI",
    _type: "experience",
    _updatedAt: "2022-11-17T07:26:32Z",
    company: "Avid Academy",
    dateEnded: "2022-05-27",
    dateStarted: "2022-02-02",
    jobTitle: "Content Developer (Intern)",
    points: [
      "Taught students programming in Javascript",
      "Created, Edited & Uploaded multiple videos for company's youtube channel",
      "Worked on Canva, Premiere Pro and Photoshop to create digital content.",
      "Increased the company video production by 150%",
    ],
  },
];
